/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE */

#include <stdint.h>

//Libreria para tipos de baroable booleanas
#include <stdbool.h>

//Libreria para operaciones matematicas
#include <math.h>

#define NOP() __asm("NOP")

void miPrimeraFuncion(void);

uint8_t getMacChar(void);

int main(void){

	miPrimeraFuncion();

	while(1){
		miPrimeraFuncion();
	}

}

void miPrimeraFuncion(void){

	//Manejo de variable booleanas

	uint8_t miPrimeraBandera = true;
	uint8_t miSegundaBandera = false;

	uint8_t XOR = miPrimeraBandera ^ miSegundaBandera;
	uint8_t OR  = miPrimeraBandera || miSegundaBandera;
	uint8_t AND = miPrimeraBandera && miSegundaBandera;

	XOR ^= 1;
	XOR ^= 1;
}
