/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE */


#include <stdint.h>

int main(void){

	uint8_t dato = 124;

	//creacion de puntero

	uint8_t *pDato;

	// Asociamos el valor en memoria al puntero
	pDato = &dato;

	//Crear una variable para almacenar el valor de memoria

	uint32_t direccionDato = (uint32_t) pDato;

	//Acceder al valor a través del puntero

	*pDato = 200;

	//Pasar a la sguiente direccion de memoria
	pDato++;

	uint8_t nuevoDato = *pDato;
}
